export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'

export const SEARCH_RECIPES = "SEARCH_RECIPES"
export const GET_RECIPE_DETAILS = "GET_RECIPE_DETAILS"


